In [3]:
import numpy as np

N = 6

# Create a one-hot matrix
one_hot = np.zeros((N, N))
one_hot[np.arange(N), np.random.randint(N, size=N)] = 1

# Create a weight matrix with normal distribution
mean = 0
std_dev = 1
weights = np.random.normal(mean, std_dev, (N, N))

print("One-Hot Matrix:")
print(one_hot)
print("\nWeight Matrix:")
print(weights)

# Calculate logits
logits = one_hot @ weights
print("\nLogits:")
print(logits)

# Calculate probabilities using softmax
softmax_probabilities = np.exp(logits) / np.sum(np.exp(logits), axis=0, keepdims=True)
print("\nSoftmax Probabilities:")
print(softmax_probabilities)

# Calculate probabilities using sigmoid
sigmoid_probabilities = 1 / (1 + np.exp(-logits))
print("\nSigmoid Probabilities:")
print(sigmoid_probabilities)

# Calculate accuracy for softmax
softmax_accuracy = np.mean(np.argmax(softmax_probabilities, axis=0) == np.argmax(one_hot, axis=0))
print("\nSoftmax Accuracy:")
print(softmax_accuracy)

# Calculate accuracy for sigmoid
sigmoid_accuracy = np.mean((sigmoid_probabilities > 0.5) == one_hot)
print("\nSigmoid Accuracy:")
print(sigmoid_accuracy)

One-Hot Matrix:
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

Weight Matrix:
[[ 0.83761973  0.26422609 -0.49629848  0.01742475 -0.21748432  1.22340958]
 [ 0.06931941 -1.30486332 -1.12193157 -0.15673709  0.20024385  0.29320358]
 [ 1.41757736 -0.35931942 -0.91730274  0.0634401  -2.17883383  0.17773641]
 [-0.36652114  0.91817341 -1.7816168   0.13421641 -1.45443688  1.13405606]
 [-0.98803448  0.77298728  0.25119122  1.3846922   0.96035618 -0.79595847]
 [-1.23000205  0.59510432  0.11899476  0.09155594 -0.52623044  1.02746428]]

Logits:
[[-0.36652114  0.91817341 -1.7816168   0.13421641 -1.45443688  1.13405606]
 [ 1.41757736 -0.35931942 -0.91730274  0.0634401  -2.17883383  0.17773641]
 [-0.36652114  0.91817341 -1.7816168   0.13421641 -1.45443688  1.13405606]
 [ 0.83761973  0.26422609 -0.49629848  0.01742475 -0.21748432  1.22340958]
 [ 1.41757736 -0.35931942 -0.91730274  0.0634401  -2.17883383  0.17773641]
 [ 1.4

In [4]:
import torch
import torch.nn.functional as F
import numpy as np

N = 6

# Create a one-hot matrix
one_hot = np.zeros((N, N))
one_hot[np.arange(N), np.random.randint(N, size=N)] = 1

# Create a weight matrix using Xavier initialization
def xavier_init(shape):
    epsilon = np.sqrt(6) / np.sqrt(np.sum(shape))
    return np.random.uniform(-epsilon, epsilon, shape)

weights = xavier_init((N, N))

print("One-Hot Matrix:")
print(one_hot)
print("\nWeight Matrix:")
print(weights)

# Convert to PyTorch tensors
one_hot_tensor = torch.tensor(one_hot, dtype=torch.float32)
weights_tensor = torch.tensor(weights, dtype=torch.float32)

# Calculate logits
logits = torch.matmul(one_hot_tensor, weights_tensor)
print("\nLogits:")
print(logits)

# Calculate probabilities using PyTorch softmax
torch_softmax_probabilities = F.softmax(logits, dim=1)
print("\nPyTorch Softmax Probabilities:")
print(torch_softmax_probabilities)

# Calculate probabilities using sigmoid
sigmoid_probabilities = 1 / (1 + np.exp(-logits.numpy()))
print("\nSigmoid Probabilities:")
print(sigmoid_probabilities)

# Calculate accuracy for PyTorch softmax
torch_softmax_accuracy = torch.mean((torch.argmax(torch_softmax_probabilities, dim=1) == torch.argmax(one_hot_tensor, dim=1)).float())
print("\nPyTorch Softmax Accuracy:")
print(torch_softmax_accuracy)

# Calculate accuracy for sigmoid
sigmoid_accuracy = np.mean((sigmoid_probabilities > 0.5) == one_hot)
print("\nSigmoid Accuracy:")
print(sigmoid_accuracy)

One-Hot Matrix:
[[0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

Weight Matrix:
[[ 0.093668    0.52251596  0.41713001  0.37318186 -0.41256222  0.65212732]
 [ 0.18587193  0.29424073 -0.67724903 -0.17752773  0.01061369 -0.0460084 ]
 [ 0.39193458  0.63390643  0.28792424  0.13985997 -0.47958734 -0.3864395 ]
 [ 0.24153936  0.09207504  0.49804628  0.08925517 -0.46829329  0.46301769]
 [ 0.54849397 -0.01632007  0.67917409 -0.56918654  0.08943282 -0.54221384]
 [-0.15286447 -0.4434299   0.37622457 -0.42970228  0.14266497  0.38642705]]

Logits:
tensor([[-0.1529, -0.4434,  0.3762, -0.4297,  0.1427,  0.3864],
        [ 0.3919,  0.6339,  0.2879,  0.1399, -0.4796, -0.3864],
        [ 0.5485, -0.0163,  0.6792, -0.5692,  0.0894, -0.5422],
        [ 0.0937,  0.5225,  0.4171,  0.3732, -0.4126,  0.6521],
        [ 0.0937,  0.5225,  0.4171,  0.3732, -0.4126,  0.6521],
        [ 0.3919,  0.6339,  0.2879,  0.1399, -0.4796, -0.3864

In [5]:
import torch
import numpy as np

N = 6

# Create a one-hot matrix
one_hot = np.zeros((N, N))
one_hot[np.arange(N), np.random.randint(N, size=N)] = 1

# Create a weight matrix using Xavier initialization
def xavier_init(shape):
    epsilon = np.sqrt(6) / np.sqrt(np.sum(shape))
    return np.random.uniform(-epsilon, epsilon, shape)

weights = xavier_init((N, N))

# Calculate logits
logits = one_hot @ weights

## Method 1: NumPy Softmax
softmax_probabilities = np.exp(logits) / np.sum(np.exp(logits), axis=1, keepdims=True)
numpy_softmax_accuracy = np.mean(np.argmax(softmax_probabilities, axis=1) == np.argmax(one_hot, axis=1))

## Method 2: PyTorch Softmax
torch_logits = torch.tensor(logits)
torch_softmax_probabilities = torch.nn.functional.softmax(torch_logits, dim=1)
torch_softmax_accuracy = torch.mean((torch.argmax(torch_softmax_probabilities, dim=1) == torch.argmax(torch.tensor(one_hot), dim=1)).float())

## Method 3: Sigmoid
sigmoid_probabilities = 1 / (1 + np.exp(-logits))
sigmoid_accuracy = np.mean((sigmoid_probabilities > 0.5) == one_hot)

print("Softmax Probabilities (NumPy):")
print(softmax_probabilities)
print("\nSoftmax Probabilities (PyTorch):")
print(torch_softmax_probabilities)
print("\nSigmoid Probabilities:")
print(sigmoid_probabilities)

print("\nAccuracy Comparison:")
print(f"NumPy Softmax Accuracy: {numpy_softmax_accuracy:.4f}")
print(f"PyTorch Softmax Accuracy: {torch_softmax_accuracy.item():.4f}")
print(f"Sigmoid Accuracy: {sigmoid_accuracy:.4f}")

if np.isclose(numpy_softmax_accuracy, torch_softmax_accuracy.item(), atol=1e-4):
    print("Softmax accuracies match.")
else:
    print("Softmax accuracies differ.")

if np.isclose(numpy_softmax_accuracy, sigmoid_accuracy, atol=1e-4):
    print("Softmax and Sigmoid accuracies match.")
else:
    print("Softmax and Sigmoid accuracies differ.")

Softmax Probabilities (NumPy):
[[0.19042168 0.08280869 0.09543444 0.13446466 0.25209838 0.24477215]
 [0.19042168 0.08280869 0.09543444 0.13446466 0.25209838 0.24477215]
 [0.08122944 0.17414603 0.0832448  0.3233764  0.11396337 0.22403996]
 [0.19042168 0.08280869 0.09543444 0.13446466 0.25209838 0.24477215]
 [0.08122944 0.17414603 0.0832448  0.3233764  0.11396337 0.22403996]
 [0.08122944 0.17414603 0.0832448  0.3233764  0.11396337 0.22403996]]

Softmax Probabilities (PyTorch):
tensor([[0.1904, 0.0828, 0.0954, 0.1345, 0.2521, 0.2448],
        [0.1904, 0.0828, 0.0954, 0.1345, 0.2521, 0.2448],
        [0.0812, 0.1741, 0.0832, 0.3234, 0.1140, 0.2240],
        [0.1904, 0.0828, 0.0954, 0.1345, 0.2521, 0.2448],
        [0.0812, 0.1741, 0.0832, 0.3234, 0.1140, 0.2240],
        [0.0812, 0.1741, 0.0832, 0.3234, 0.1140, 0.2240]], dtype=torch.float64)

Sigmoid Probabilities:
[[0.57509597 0.37050888 0.40416806 0.48868544 0.64181535 0.63500759]
 [0.57509597 0.37050888 0.40416806 0.48868544 0.64181535 